const challengeCards=["What small thing always makes you laugh?","Tell a story about a time you got wonderfully lost.","If your life had a theme song, what would it be?","What invention would you love to thank its inventor for?","Share a food memory you would happily relive.","Describe your perfect lazy day without using the word 'relax'.","What is a skill you wish you could instantly learn?","Make your best sound effect for a rainy day."];
const teamCards=["Invent a handshake with three moves and perform it.","Agree on one place you would both love to visit and explain why.","Create a two-line story, taking turns with one line each.","Find three things you have in common in 30 seconds.","Choose an object in the room and give it a dramatic new name.","Tell a shared story: one person starts, the other gives it an ending."];
const objects=["telephone","camera","radio","bicycle","school bag","watch","record player","newspaper","video game controller","television remote","alarm clock","photograph"];
const spaceTypes=["challenge","team","object","talk","act","wild","swap","life","lose"];
const spaceIcons={challenge:"?",team:"?!",object:"🧩",talk:"🎤",act:"🎭",plain:"·",wild:"🃏",swap:"↔",life:"♥",lose:"💔"};
const state={roomId:"",mode:"same",teamNames:["The Storytellers","The Adventurers"],turn:0,positions:[0,0],routes:["safe","safe"],hearts:[3,3],dice:null,gameStarted:false,guestConnected:false,ended:false,used:[],sound:true};
let channel;
const $=id=>document.getElementById(id);
const screens={home:"homeScreen",setup:"setupScreen",join:"joinScreen",lobby:"lobbyScreen",game:"gameScreen",rules:"rulesScreen"};
function showScreen(name){Object.values(screens).forEach(id=>$(id).classList.remove("active"));$(screens[name]).classList.add("active");window.scrollTo(0,0)}
document.querySelectorAll("[data-screen]").forEach(el=>el.addEventListener("click",()=>showScreen(el.dataset.screen)));
$("createGameButton").onclick=()=>{state.roomId=makeCode();state.mode="same";state.guestConnected=false;$("roomCodePreview").textContent=state.roomId;document.querySelectorAll(".mode-choice").forEach(item=>item.classList.toggle("selected",item.dataset.mode==="same"));$("sameDeviceFields").hidden=false;$("differentDeviceFields").hidden=true;saveRoom();showScreen("setup")};
$("hostTeamInput").value=state.teamNames[0];
document.querySelectorAll(".mode-choice").forEach(button=>button.onclick=()=>{state.mode=button.dataset.mode;document.querySelectorAll(".mode-choice").forEach(item=>item.classList.toggle("selected",item===button));$("sameDeviceFields").hidden=state.mode!=="same";$("differentDeviceFields").hidden=state.mode==="same";$("teamTwoInput").disabled=state.mode!=="same";});
$("joinGameButton").onclick=()=>showScreen("join");
$("rulesStartButton").onclick=()=>{$("createGameButton").click()};
$("copyCodeButton").onclick=async()=>{try{await navigator.clipboard.writeText(state.roomId);$("copyMessage").textContent="Room code copied — invite your teammate!";toast("Room code copied")}catch{$("copyMessage").textContent="Your room code is "+state.roomId}};
$("lobbyButton").onclick=()=>{state.teamNames=state.mode==="same"?[$("teamOneInput").value.trim()||"Team 1",$("teamTwoInput").value.trim()||"Team 2"]:[$("hostTeamInput").value.trim()||"Team 1","Waiting for teammate"];state.gameStarted=false;setupLobby();showScreen("lobby");saveRoom();broadcast()};
$("joinConfirmButton").onclick=()=>{const code=$("joinCodeInput").value.trim().toUpperCase();if(code.length!==6){$("joinMessage").textContent="Please enter a six-character room code.";return}const saved=readRoom(code);if(!saved){$("joinMessage").textContent="Room not found. The host must create and share the room from the same browser environment.";return}state.roomId=code;state.mode="different";state.teamNames=[saved.teamNames[0],$("joinTeamInput").value.trim()||"Team 2"];state.gameStarted=saved.gameStarted;state.guestConnected=true;setupLobby();showScreen(state.gameStarted?"game":"lobby");if(state.gameStarted)renderBoard();saveRoom();broadcast();toast("Joined room "+code)};
$("startGameButton").onclick=()=>{state.gameStarted=true;initGame();showScreen("game");saveRoom();broadcast()};
$("rollButton").onclick=rollDice;
document.querySelectorAll(".route-choice-button").forEach(button=>button.onclick=()=>chooseRoute(button.dataset.route));
$("board").addEventListener("click",event=>{const space=event.target.closest(".space");if(space) showSpaceInfo(Number(space.dataset.index))});
document.querySelectorAll(".deck").forEach(deck=>deck.onclick=()=>drawDeck(deck.dataset.deck));
$("soundToggle").onclick=()=>{state.sound=!state.sound;$("soundToggle").textContent=state.sound?"🔊":"🔇"};
$("rulesButton").onclick=()=>openModal("How to play",`<p>Roll, move and complete whatever the board gives you. Safe Route is longer and gentler; Risk Route is shorter with bolder challenges.</p><p>Keep your hearts, listen closely and let the stories do the winning.</p>`);
$("quitButton").onclick=()=>showScreen("home");
$("modalClose").onclick=closeModal;
$("modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")closeModal()};
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function roomKey(code=state.roomId){return `across-the-ages-room-${code}`}
function saveRoom(){if(!state.roomId)return;localStorage.setItem(roomKey(),JSON.stringify(state))}
function readRoom(code){try{const saved=localStorage.getItem(roomKey(code));return saved?JSON.parse(saved):null}catch{return null}}
function setupLobby(){$("lobbyCode").textContent=state.roomId;$("lobbyTeamOne").textContent=state.teamNames[0];$("lobbyTeamTwo").textContent=state.teamNames[1];$("guestStatus").textContent=state.mode==="same"?"Same device · both teams ready":state.guestConnected?"Player connected ✓":"Waiting for the other player…";$("guestPill").textContent=state.mode==="same"||state.guestConnected?"READY":"WAITING";$("guestPill").classList.toggle("waiting",state.mode!=="same"&&!state.guestConnected);$("startGameButton").disabled=state.mode==="different"&&!state.guestConnected}
function buildSpaces(){const safe=["object","challenge","team","talk","object","act","challenge","life","team","object","talk","challenge","object","team","act","object","swap","challenge","life","team","object","talk","challenge","object","team","life","object","challenge","talk","object"];const risk=["act","wild","talk","lose","object","challenge","life","team","object","act","lose","object","challenge","team","talk","object","lose","life"];return [{type:"start",route:"start"},...safe.map(type=>({type,route:"safe"})),...risk.map(type=>({type,route:"risk"})),{type:"finish",route:"finish"}]}
const spaces=buildSpaces();
const safePath=[0,...Array.from({length:30},(_,i)=>i+1),49],riskPath=[0,1,2,3,4,5,...Array.from({length:18},(_,i)=>i+31),30,49];
const safeCoordinates=[[16,86],[25,86],[34,86],[43,86],[52,86],[61,86],[70,86],[79,86],[91,77],[91,67],[91,57],[91,47],[91,37],[91,27],[79,16],[69,16],[59,16],[49,16],[39,16],[29,16],[19,16],[8,27],[8,37],[8,47],[8,57],[8,67],[8,77],[18,72],[28,72],[38,72]];
const riskCoordinates=[[20,53],[28,53],[36,53],[44,53],[52,53],[60,53],[68,53],[76,53],[84,53],[84,40],[76,40],[68,40],[60,40],[52,40],[44,40],[36,40],[28,40],[20,40]];
function initGame(){state.positions=[0,0];state.routes=["safe","safe"];state.hearts=[3,3];state.turn=0;state.dice=null;state.ended=false;state.used=[];$("gameRoomCode").textContent=state.roomId;$("gameTeamOne").textContent=state.teamNames[0];$("gameTeamTwo").textContent=state.teamNames[1];$("dieOne").textContent="?";$("dieTwo").textContent="?";$("diceTotal").textContent="—";renderBoard();updateGameUi();log("The game has begun. "+state.teamNames[0]+" goes first!")}
function routeCoordinates(index,route){if(index===0)return [5,86];if(index===49)return [94,86];if(route==="safe")return safeCoordinates[index-1];return riskCoordinates[index-31]}
function renderBoard(){const board=$("board");board.innerHTML="";spaces.forEach((space,i)=>{const el=document.createElement("div");el.className=`space ${space.route}-space ${i===0?"start":""} ${i===49?"finish":""}`;el.dataset.index=i;const [left,top]=routeCoordinates(i,space.route);el.style.left=`${left}%`;el.style.top=`${top}%`;const label=i===0?"START":i===49?"FINISH":space.route==="safe"?`S${i}`:`R${i-30}`;el.innerHTML=`<span class="space-icon">${i===0?"●":i===49?"🏁":spaceIcons[space.type]}</span><span>${label}</span>`;board.appendChild(el)});for(let t=0;t<2;t++){const pawn=document.createElement("div");pawn.id="pawn"+t;pawn.className=`pawn ${t===0?"one":"two"}`;pawn.textContent=t+1;board.appendChild(pawn)}placePawns()}
function placePawns(){for(let t=0;t<2;t++){const cell=$(`board`).querySelector(`[data-index="${state.positions[t]}"]`);const pawn=$(`pawn${t}`);if(cell&&pawn){pawn.style.left=`${cell.offsetLeft+cell.offsetWidth/2-15}px`;pawn.style.top=`${cell.offsetTop+cell.offsetHeight/2-15}px`}document.querySelectorAll(".space").forEach(el=>el.classList.toggle("current",state.positions.includes(Number(el.dataset.index))))}}
window.addEventListener("resize",placePawns);
function updateGameUi(){$("turnHeading").textContent=`${state.teamNames[state.turn]}'s turn`;$("turnLabel").textContent=`TEAM ${state.turn+1}`;$("heartsOne").textContent="♥".repeat(state.hearts[0])+"♡".repeat(3-state.hearts[0]);$("heartsTwo").textContent="♥".repeat(state.hearts[1])+"♡".repeat(3-state.hearts[1]);$("heartsOne").setAttribute("aria-label",`${state.hearts[0]} hearts`);$("heartsTwo").setAttribute("aria-label",`${state.hearts[1]} hearts`);$("rollButton").disabled=state.ended;const routeLocked=state.positions[state.turn]>4;document.querySelectorAll(".route-choice-button").forEach(b=>{b.classList.toggle("selected",b.dataset.route===state.routes[state.turn]);b.disabled=routeLocked||state.ended});$("routeMessage").textContent=routeLocked?`${state.routes[state.turn]==="safe"?"Safe Route":"Risk Route"} locked in — keep moving.`:`${state.routes[state.turn]==="safe"?"Safe Route: longer, steadier":"Risk Route: shortcut, more dangerous"}`;const pos=state.positions[state.turn];$("activityTitle").textContent=state.ended?"Game complete":pos===0?"Move through the shared start, then choose your branch":`${spaces[pos].type.replace("-"," ")} space`;$("activityText").textContent=state.ended?"Start a new room to play again.":"Click a board space or deck to preview its activity."}
function chooseRoute(route){if(state.ended||state.positions[state.turn]>4){toast("Your route is already locked in.");return}state.routes[state.turn]=route;updateGameUi();log(`${state.teamNames[state.turn]} chose the ${route} route.`);broadcast()}
async function rollDice(){if(state.ended)return;$("rollButton").disabled=true;$("diceMessage").textContent="Rolling both dice…";let count=0;const animation=setInterval(()=>{$("dieOne").textContent=Math.ceil(Math.random()*3);$("dieTwo").textContent=Math.ceil(Math.random()*2);if(++count>7){clearInterval(animation);finishRoll()}},70)}
function findPathIndex(path,position){const exact=path.indexOf(position);return exact>=0?exact:0}
function finishRoll(){const dieOne=Math.ceil(Math.random()*3),dieTwo=Math.ceil(Math.random()*2),roll=Math.min(5,dieOne+dieTwo);state.dice={dieOne,dieTwo,total:roll};$("dieOne").textContent=dieOne;$("dieTwo").textContent=dieTwo;$("diceTotal").textContent=roll;$("diceMessage").textContent=`${state.teamNames[state.turn]} rolled ${dieOne} + ${dieTwo} · max 5 spaces`;log(`${state.teamNames[state.turn]} rolled ${dieOne} + ${dieTwo} = ${roll}.`);const team=state.turn;const path=state.routes[team]==="risk"?riskPath:safePath;const pathIndex=findPathIndex(path,state.positions[team]);const target=path[Math.min(pathIndex+roll,path.length-1)];let steps=0;const move=setInterval(()=>{if(steps++>=roll||state.positions[team]===target){clearInterval(move);activateSpace(team);return}const nextIndex=findPathIndex(path,state.positions[team])+1;state.positions[team]=path[nextIndex]??target;placePawns()},240)}
function activateSpace(team){const position=state.positions[team],space=spaces[position];log(`${state.teamNames[team]} landed on ${space.type.replace("-"," ")}.`);if(position===49){endGame(team);return}if(space.type==="lose"){changeHeart(team,-1);openModal("A heart is lost",`<p class="prompt">💔 -1 LIFE</p><p>Your team lost 1 life. Keep the conversation going.</p>`,[{label:"Continue",action:closeModal}]);}else if(space.type==="life"){changeHeart(team,1);openModal("A heart is gained",`<p class="prompt">♥ +1 life</p><p>Your team feels a little more unstoppable.</p>`,[{label:"Continue",action:closeModal}]);}else if(space.type==="challenge")cardModal("Challenge Card",challengeCards,team);else if(space.type==="object")objectModal(team);else if(space.type==="team")cardModal("Team Challenge Card",teamCards,team);else if(space.type==="talk")secretModal(team);else if(space.type==="act")cardModal(space.route==="risk"?"Acting Jeopardy · 02:00":"Act It Out · no time limit",space.route==="risk"?objects.map(x=>`Act out: ${x}`):objects,team,space.route==="risk");else if(space.type==="wild")wildModal(team);else if(space.type==="swap")swapModal(team);nextTurn()}
function nextTurn(){if(!state.ended){state.turn=1-state.turn;updateGameUi();broadcast()}}
function changeHeart(team,amount){state.hearts[team]=Math.max(0,Math.min(3,state.hearts[team]+amount));updateGameUi();if(state.hearts[team]===0)endGame(1-team)}
function endGame(winner){state.ended=true;updateGameUi();openModal("Game complete",`<h2>🏆 ${state.teamNames[winner]} wins!</h2><p>You made it all the way through Kindred Quest. The best part is the stories you shared along the way.</p>`,[{label:"Play again",action:()=>{closeModal();initGame()}},{label:"Return home",action:()=>{closeModal();showScreen("home")}}]);log(`${state.teamNames[winner]} won the game!`)}
function pick(list){const available=list.filter((_,i)=>!state.used.includes(`${list===objects?"o":"c"}${i}`));const item=(available.length?available:list)[Math.floor(Math.random()*(available.length?available.length:list.length))];const index=list.indexOf(item);state.used.push(`${list===objects?"o":"c"}${index}`);return item}
function cardModal(title,list,team,jeopardy=false){const card=pick(list);let timerHtml=jeopardy?`<div class="timer" id="timer">02:00</div>`:"";openModal(title,`<div class="eyebrow">For ${state.teamNames[team]}</div><h2>${title}</h2><div class="prompt">${card}</div>${timerHtml}<p>${jeopardy?"Act out both objects before the timer reaches zero.":"Take your time — there are no wrong answers."}</p>`,[{label:"Done — continue",action:closeModal}]);if(jeopardy)startTimer()}
function objectModal(team){const object=pick(objects);openModal("Object Card",`<div class="eyebrow">Drawn from the Object Deck · for ${state.teamNames[team]}</div><h2>🧩 Object Card</h2><div class="prompt">${object.toUpperCase()}</div><p>Use this object for a memory, a comparison between generations, a guess or a story.</p>`,[{label:"Done — continue",action:closeModal}])}
function drawDeck(deck){if(deck==="challenge")cardModal("Challenge Card",challengeCards,state.turn);if(deck==="object")objectModal(state.turn);if(deck==="team")cardModal("Team Challenge Card",teamCards,state.turn);toast(`${deck==="team"?"Team challenge":deck[0].toUpperCase()+deck.slice(1)} card drawn`)}
function showSpaceInfo(index){const space=spaces[index];const labels={challenge:"Draw a Challenge Card: one person completes the prompt.",object:"Draw an Object Card: use it for a memory, guess or story.",team:"Draw a Team Challenge Card: both teammates participate.",talk:"Talk It Out: one player receives a secret prompt.",act:space.route==="risk"?"Acting Jeopardy: act out two objects in 2 minutes.":"Act It Out: act out one object with no time limit.",wild:"Wild Card: the opposing team chooses two Safe Route challenges.",swap:"Swap Place: exchange positions with the other pawn.",life:"Gain Heart: add one life, up to three.",lose:"-1 Life: lose one heart.",plain:"Route marker"};openModal(`${space.route==="risk"?"Risk":"Safe"} Route · Space ${index+1}`,`<h2>${spaceIcons[space.type]} ${space.type.replace("-"," ").toUpperCase()}</h2><p>${labels[space.type]}</p><p class="modal-hint">This space activates automatically when a pawn lands here.</p>`)}
function secretModal(team){const word=pick(objects);openModal("Talk It Out",`<div class="eyebrow">Secret prompt for ${state.teamNames[team]}</div><h2>🎤 Talk It Out</h2><div class="prompt">🔒 Only the selected player can see this<br><br><strong>${word.toUpperCase()}</strong></div><p>Give clues without saying the word. Everyone else: listen closely and guess!</p>`,[{label:"Done — continue",action:closeModal}])}
function wildModal(team){const picks=[pick(challengeCards),pick(challengeCards)];openModal("🃏 Wild Card",`<h2>Two challenges chosen</h2><p>The opposing team chose these for <strong>${state.teamNames[team]}</strong>:</p><div class="prompt">1. ${picks[0]}<br><br>2. ${picks[1]}</div><p>Complete both before continuing.</p>`,[{label:"Done — continue",action:closeModal}])}
function swapModal(team){const other=1-team;[state.positions[team],state.positions[other]]=[state.positions[other],state.positions[team]];placePawns();openModal("↔ Swap Place",`<h2>Pawns swapped!</h2><p>${state.teamNames[team]} and ${state.teamNames[other]} have traded places — no matter which route they were on.</p>`,[{label:"Continue",action:closeModal}]);log("The teams swapped places.");}
function startTimer(){let seconds=120;const el=$("timer");const timer=setInterval(()=>{seconds--;if(!el||seconds<=0){clearInterval(timer);if(el)el.textContent="00:00";return}if(el)el.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`},1000)}
function openModal(title,html,actions=[]){$("modalContent").innerHTML=`<div class="eyebrow">${title}</div>${html}${actions.length?`<div class="modal-actions">${actions.map((a,i)=>`<button class="${i===0?"primary-button":"secondary-button"}" data-modal-action="${i}">${a.label}</button>`).join("")}</div>`:""}`;$("modalBackdrop").hidden=false;actions.forEach((a,i)=>document.querySelector(`[data-modal-action="${i}"]`).onclick=a.action)}
function closeModal(){$("modalBackdrop").hidden=true}
function log(message){const p=document.createElement("p");p.innerHTML=`<b>${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</b> ${message}`;$("gameLog").prepend(p)}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function broadcast(){if(!state.roomId)return;saveRoom();if(channel)channel.postMessage({type:"state",state:{...state}})}
function applyRemote(remote){if(!remote||remote.roomId!==state.roomId)return;Object.assign(state,remote);setupLobby();if(state.gameStarted){showScreen("game");renderBoard();updateGameUi()}}
try{channel=new BroadcastChannel("across-the-ages");channel.onmessage=e=>{if(e.data.type==="state")applyRemote(e.data.state)}}catch{document.querySelector(".connection-status").innerHTML="<i>•</i> Local play"}
window.addEventListener("storage",event=>{if(event.key===roomKey()&&event.newValue){try{applyRemote(JSON.parse(event.newValue))}catch{}}});
